//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parduotuve_povbuk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DuomenuBaze.m" +
            "df;Integrated Security=True")]
        public string DuomenuBazeConnectionString {
            get {
                return ((string)(this["DuomenuBazeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\POVILAS\\SOURCE\\REPOS\\" +
            "PARDUOTUVE_POVBUK\\PARDUOTUVE_POVBUK\\BIN\\DEBUG\\DUOMENUBAZE.MDF;Integrated Securit" +
            "y=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string C__USERS_POVILAS_SOURCE_REPOS_PARDUOTUVE_POVBUK_PARDUOTUVE_POVBUK_BIN_DEBUG_DUOMENUBAZE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_POVILAS_SOURCE_REPOS_PARDUOTUVE_POVBUK_PARDUOTUVE_POVBUK_BIN_DEBUG_DUOME" +
                    "NUBAZE_MDFConnectionString"]));
            }
        }
    }
}
