#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parduotuve_povbuk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\USERS\\POVILAS\\SOURCE\\REPOS\\PARDUOTUVE_POVBUK\\PARDUOTUVE_POVBUK\\BIN\\DEBUG\\DUOME" +
		"NUBAZE.MDF")]
	public partial class KonverterisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVartotojai(Vartotojai instance);
    partial void UpdateVartotojai(Vartotojai instance);
    partial void DeleteVartotojai(Vartotojai instance);
    partial void InsertUzsakymai(Uzsakymai instance);
    partial void UpdateUzsakymai(Uzsakymai instance);
    partial void DeleteUzsakymai(Uzsakymai instance);
    partial void InsertPreke(Preke instance);
    partial void UpdatePreke(Preke instance);
    partial void DeletePreke(Preke instance);
    partial void InsertIrasai(Irasai instance);
    partial void UpdateIrasai(Irasai instance);
    partial void DeleteIrasai(Irasai instance);
    #endregion
		
		public KonverterisDataContext() : 
				base(global::Parduotuve_povbuk.Properties.Settings.Default.C__USERS_POVILAS_SOURCE_REPOS_PARDUOTUVE_POVBUK_PARDUOTUVE_POVBUK_BIN_DEBUG_DUOMENUBAZE_MDFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonverterisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vartotojai> Vartotojais
		{
			get
			{
				return this.GetTable<Vartotojai>();
			}
		}
		
		public System.Data.Linq.Table<Uzsakymai> Uzsakymais
		{
			get
			{
				return this.GetTable<Uzsakymai>();
			}
		}
		
		public System.Data.Linq.Table<Preke> Prekes
		{
			get
			{
				return this.GetTable<Preke>();
			}
		}
		
		public System.Data.Linq.Table<Irasai> Irasais
		{
			get
			{
				return this.GetTable<Irasai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vartotojai")]
	public partial class Vartotojai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Vartotojo_ID;
		
		private string _Vardas;
		
		private string _Pavarde;
		
		private System.Nullable<System.DateTime> _Gimimo_data;
		
		private string _Adresas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVartotojo_IDChanging(int value);
    partial void OnVartotojo_IDChanged();
    partial void OnVardasChanging(string value);
    partial void OnVardasChanged();
    partial void OnPavardeChanging(string value);
    partial void OnPavardeChanged();
    partial void OnGimimo_dataChanging(System.Nullable<System.DateTime> value);
    partial void OnGimimo_dataChanged();
    partial void OnAdresasChanging(string value);
    partial void OnAdresasChanged();
    #endregion
		
		public Vartotojai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vartotojo ID]", Storage="_Vartotojo_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Vartotojo_ID
		{
			get
			{
				return this._Vartotojo_ID;
			}
			set
			{
				if ((this._Vartotojo_ID != value))
				{
					this.OnVartotojo_IDChanging(value);
					this.SendPropertyChanging();
					this._Vartotojo_ID = value;
					this.SendPropertyChanged("Vartotojo_ID");
					this.OnVartotojo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vardas", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Vardas
		{
			get
			{
				return this._Vardas;
			}
			set
			{
				if ((this._Vardas != value))
				{
					this.OnVardasChanging(value);
					this.SendPropertyChanging();
					this._Vardas = value;
					this.SendPropertyChanged("Vardas");
					this.OnVardasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavarde", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pavarde
		{
			get
			{
				return this._Pavarde;
			}
			set
			{
				if ((this._Pavarde != value))
				{
					this.OnPavardeChanging(value);
					this.SendPropertyChanging();
					this._Pavarde = value;
					this.SendPropertyChanged("Pavarde");
					this.OnPavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Gimimo data]", Storage="_Gimimo_data", DbType="Date")]
		public System.Nullable<System.DateTime> Gimimo_data
		{
			get
			{
				return this._Gimimo_data;
			}
			set
			{
				if ((this._Gimimo_data != value))
				{
					this.OnGimimo_dataChanging(value);
					this.SendPropertyChanging();
					this._Gimimo_data = value;
					this.SendPropertyChanged("Gimimo_data");
					this.OnGimimo_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresas", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adresas
		{
			get
			{
				return this._Adresas;
			}
			set
			{
				if ((this._Adresas != value))
				{
					this.OnAdresasChanging(value);
					this.SendPropertyChanging();
					this._Adresas = value;
					this.SendPropertyChanged("Adresas");
					this.OnAdresasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzsakymai")]
	public partial class Uzsakymai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Uzsakymo_ID;
		
		private string _Vartotojo_ID;
		
		private System.Nullable<int> _Kaina;
		
		private string _Adresas;
		
		private System.Nullable<int> _Atsiskaitymo_tipas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUzsakymo_IDChanging(int value);
    partial void OnUzsakymo_IDChanged();
    partial void OnVartotojo_IDChanging(string value);
    partial void OnVartotojo_IDChanged();
    partial void OnKainaChanging(System.Nullable<int> value);
    partial void OnKainaChanged();
    partial void OnAdresasChanging(string value);
    partial void OnAdresasChanged();
    partial void OnAtsiskaitymo_tipasChanging(System.Nullable<int> value);
    partial void OnAtsiskaitymo_tipasChanged();
    #endregion
		
		public Uzsakymai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Uzsakymo ID]", Storage="_Uzsakymo_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Uzsakymo_ID
		{
			get
			{
				return this._Uzsakymo_ID;
			}
			set
			{
				if ((this._Uzsakymo_ID != value))
				{
					this.OnUzsakymo_IDChanging(value);
					this.SendPropertyChanging();
					this._Uzsakymo_ID = value;
					this.SendPropertyChanged("Uzsakymo_ID");
					this.OnUzsakymo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Vartotojo ID]", Storage="_Vartotojo_ID", DbType="NVarChar(50)")]
		public string Vartotojo_ID
		{
			get
			{
				return this._Vartotojo_ID;
			}
			set
			{
				if ((this._Vartotojo_ID != value))
				{
					this.OnVartotojo_IDChanging(value);
					this.SendPropertyChanging();
					this._Vartotojo_ID = value;
					this.SendPropertyChanged("Vartotojo_ID");
					this.OnVartotojo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaina", DbType="Int")]
		public System.Nullable<int> Kaina
		{
			get
			{
				return this._Kaina;
			}
			set
			{
				if ((this._Kaina != value))
				{
					this.OnKainaChanging(value);
					this.SendPropertyChanging();
					this._Kaina = value;
					this.SendPropertyChanged("Kaina");
					this.OnKainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresas", DbType="NVarChar(50)")]
		public string Adresas
		{
			get
			{
				return this._Adresas;
			}
			set
			{
				if ((this._Adresas != value))
				{
					this.OnAdresasChanging(value);
					this.SendPropertyChanging();
					this._Adresas = value;
					this.SendPropertyChanged("Adresas");
					this.OnAdresasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Atsiskaitymo tipas]", Storage="_Atsiskaitymo_tipas", DbType="Int")]
		public System.Nullable<int> Atsiskaitymo_tipas
		{
			get
			{
				return this._Atsiskaitymo_tipas;
			}
			set
			{
				if ((this._Atsiskaitymo_tipas != value))
				{
					this.OnAtsiskaitymo_tipasChanging(value);
					this.SendPropertyChanging();
					this._Atsiskaitymo_tipas = value;
					this.SendPropertyChanged("Atsiskaitymo_tipas");
					this.OnAtsiskaitymo_tipasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prekes")]
	public partial class Preke : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Prekes_ID;
		
		private string _Pavadinimas;
		
		private System.Nullable<int> _Kaina;
		
		private System.Nullable<int> _Kiekis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrekes_IDChanging(int value);
    partial void OnPrekes_IDChanged();
    partial void OnPavadinimasChanging(string value);
    partial void OnPavadinimasChanged();
    partial void OnKainaChanging(System.Nullable<int> value);
    partial void OnKainaChanged();
    partial void OnKiekisChanging(System.Nullable<int> value);
    partial void OnKiekisChanged();
    #endregion
		
		public Preke()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prekes ID]", Storage="_Prekes_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Prekes_ID
		{
			get
			{
				return this._Prekes_ID;
			}
			set
			{
				if ((this._Prekes_ID != value))
				{
					this.OnPrekes_IDChanging(value);
					this.SendPropertyChanging();
					this._Prekes_ID = value;
					this.SendPropertyChanged("Prekes_ID");
					this.OnPrekes_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavadinimas", DbType="NVarChar(50)")]
		public string Pavadinimas
		{
			get
			{
				return this._Pavadinimas;
			}
			set
			{
				if ((this._Pavadinimas != value))
				{
					this.OnPavadinimasChanging(value);
					this.SendPropertyChanging();
					this._Pavadinimas = value;
					this.SendPropertyChanged("Pavadinimas");
					this.OnPavadinimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaina", DbType="Int")]
		public System.Nullable<int> Kaina
		{
			get
			{
				return this._Kaina;
			}
			set
			{
				if ((this._Kaina != value))
				{
					this.OnKainaChanging(value);
					this.SendPropertyChanging();
					this._Kaina = value;
					this.SendPropertyChanged("Kaina");
					this.OnKainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kiekis", DbType="Int")]
		public System.Nullable<int> Kiekis
		{
			get
			{
				return this._Kiekis;
			}
			set
			{
				if ((this._Kiekis != value))
				{
					this.OnKiekisChanging(value);
					this.SendPropertyChanging();
					this._Kiekis = value;
					this.SendPropertyChanged("Kiekis");
					this.OnKiekisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Irasai")]
	public partial class Irasai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Iraso_ID;
		
		private System.Nullable<int> _Uzsakymo_ID;
		
		private System.Nullable<int> _Prekes_ID;
		
		private System.Nullable<int> _Kaina;
		
		private System.Nullable<int> _Kiekis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIraso_IDChanging(int value);
    partial void OnIraso_IDChanged();
    partial void OnUzsakymo_IDChanging(System.Nullable<int> value);
    partial void OnUzsakymo_IDChanged();
    partial void OnPrekes_IDChanging(System.Nullable<int> value);
    partial void OnPrekes_IDChanged();
    partial void OnKainaChanging(System.Nullable<int> value);
    partial void OnKainaChanged();
    partial void OnKiekisChanging(System.Nullable<int> value);
    partial void OnKiekisChanged();
    #endregion
		
		public Irasai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Iraso ID]", Storage="_Iraso_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Iraso_ID
		{
			get
			{
				return this._Iraso_ID;
			}
			set
			{
				if ((this._Iraso_ID != value))
				{
					this.OnIraso_IDChanging(value);
					this.SendPropertyChanging();
					this._Iraso_ID = value;
					this.SendPropertyChanged("Iraso_ID");
					this.OnIraso_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Uzsakymo ID]", Storage="_Uzsakymo_ID", DbType="Int")]
		public System.Nullable<int> Uzsakymo_ID
		{
			get
			{
				return this._Uzsakymo_ID;
			}
			set
			{
				if ((this._Uzsakymo_ID != value))
				{
					this.OnUzsakymo_IDChanging(value);
					this.SendPropertyChanging();
					this._Uzsakymo_ID = value;
					this.SendPropertyChanged("Uzsakymo_ID");
					this.OnUzsakymo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prekes ID]", Storage="_Prekes_ID", DbType="Int")]
		public System.Nullable<int> Prekes_ID
		{
			get
			{
				return this._Prekes_ID;
			}
			set
			{
				if ((this._Prekes_ID != value))
				{
					this.OnPrekes_IDChanging(value);
					this.SendPropertyChanging();
					this._Prekes_ID = value;
					this.SendPropertyChanged("Prekes_ID");
					this.OnPrekes_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaina", DbType="Int")]
		public System.Nullable<int> Kaina
		{
			get
			{
				return this._Kaina;
			}
			set
			{
				if ((this._Kaina != value))
				{
					this.OnKainaChanging(value);
					this.SendPropertyChanging();
					this._Kaina = value;
					this.SendPropertyChanged("Kaina");
					this.OnKainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kiekis", DbType="Int")]
		public System.Nullable<int> Kiekis
		{
			get
			{
				return this._Kiekis;
			}
			set
			{
				if ((this._Kiekis != value))
				{
					this.OnKiekisChanging(value);
					this.SendPropertyChanging();
					this._Kiekis = value;
					this.SendPropertyChanged("Kiekis");
					this.OnKiekisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
